
###
POST http://localhost:3001/api/products
Content-Type: application/json

{
   "product_name" : "iPhone 8 Plus",
   "product_ascii": "iphone_8_plus",
   "category_id": "1"
}


###
POST http://localhost:3001/api/categories
Content-Type: application/json

{
   "category_name" : "Mobile",
   "category_ascii": "mobile"
}


###
POST http://localhost:3001/api/categories/attributes
Content-Type: application/json

{
   "category_id": "1",
  "attribute_name": "GPU",
  "attribute_ascii": "gpu"
}

###
GET http://localhost:3001/api/products?page=1&category_id=1

###
GET http://localhost:3001/api/products/iphone-14-pro

###
GET  http://localhost:3001/api/categories

###
GET  http://localhost:3001/api/images?page=1